import type { UserProfile, Mentor, LearningResource, ProgressRecord, ActivityLog } from './types';
export const profile: UserProfile = {name:'Aarav Sharma',education:'B.Tech Information Technology',careerGoal:'AI / Machine Learning Engineer',skills:['Python','C++','Machine Learning Basics','Data Structures','Git'],desiredSkills:['Deep Learning','MLOps','Cloud Computing'],interests:['AI','Data Science','Cloud','Software Engineering']};
export const mentors: Mentor[] = [
{id:'m1',name:'Ananya Rao',title:'Senior Machine Learning Engineer',company:'Microsoft',experience:8,domain:'AI / Machine Learning',expertise:['Deep Learning','MLOps','Python'],skills:['Python','Machine Learning Basics','Deep Learning','MLOps','Git','Data Structures'],focus:'From ML fundamentals to production-ready models',bio:'Ananya builds applied machine learning systems and helps early engineers bridge the gap between notebooks and production. Her mentoring centers on practical projects and strong foundations.',interests:['AI','Data Science','Software Engineering'],color:'peach'},
{id:'m2',name:'Rohan Mehta',title:'ML Platform Engineer',company:'Google',experience:7,domain:'MLOps',expertise:['MLOps','Cloud Computing','Docker'],skills:['Python','Git','MLOps','Cloud Computing','Docker','Machine Learning Basics'],focus:'Building reliable machine learning infrastructure',bio:'Rohan works at the intersection of machine learning and cloud infrastructure. He guides learners through model deployment, repeatable experiments, and portfolio projects.',interests:['AI','Cloud','Software Engineering'],color:'blue'},
{id:'m3',name:'Priya Nair',title:'Applied AI Researcher',company:'Adobe',experience:9,domain:'AI / Machine Learning',expertise:['Deep Learning','Computer Vision','Python'],skills:['Python','C++','Machine Learning Basics','Data Structures','Deep Learning','Git'],focus:'Deep learning foundations and research-to-product thinking',bio:'Priya turns research ideas into useful AI applications. She enjoys helping students understand neural networks through thoughtful experiments and clear explanations.',interests:['AI','Data Science'],color:'lilac'},
{id:'m4',name:'Vikram Shah',title:'Principal Data Scientist',company:'IBM',experience:11,domain:'Data Science',expertise:['Statistics','Python','Machine Learning Basics'],skills:['Python','Machine Learning Basics','SQL','Statistics','Git'],focus:'Experiment design and data science career foundations',bio:'Vikram helps learners develop sound statistical intuition and communicate the business value of their data projects.',interests:['AI','Data Science'],color:'mint'},
{id:'m5',name:'Isha Kapoor',title:'Cloud Solutions Architect',company:'Amazon Web Services',experience:8,domain:'Cloud Computing',expertise:['Cloud Computing','AWS','Docker'],skills:['Cloud Computing','Python','Git','Docker','Networking'],focus:'Cloud architecture through hands-on projects',bio:'Isha designs resilient cloud systems and helps new engineers understand infrastructure, deployment, and the decisions behind system architecture.',interests:['Cloud','Software Engineering'],color:'peach'},
{id:'m6',name:'Arjun Desai',title:'Senior DevOps Engineer',company:'Atlassian',experience:6,domain:'DevOps',expertise:['Docker','Kubernetes','CI/CD'],skills:['Git','Python','Docker','Cloud Computing','Kubernetes'],focus:'Practical deployment and engineering workflows',bio:'Arjun teaches the foundations of reliable software delivery through small, practical infrastructure projects.',interests:['Cloud','DevOps','Software Engineering'],color:'blue'},
{id:'m7',name:'Sana Ahmed',title:'Security Engineer',company:'Cisco',experience:7,domain:'Cybersecurity',expertise:['Networking','Security','Python'],skills:['Python','C++','Networking','Security','Git'],focus:'Security fundamentals and defensive engineering',bio:'Sana helps students build a grounded understanding of application and network security, with an emphasis on responsible defensive practice.',interests:['Cybersecurity','Software Engineering'],color:'lilac'},
{id:'m8',name:'Kabir Sethi',title:'Staff Full Stack Engineer',company:'Razorpay',experience:9,domain:'Full Stack Development',expertise:['React','TypeScript','Node.js'],skills:['React','TypeScript','Node.js','Git','Data Structures'],focus:'Building complete products and a strong portfolio',bio:'Kabir guides developers from isolated tutorials to complete applications, with attention to maintainability and user experience.',interests:['Full Stack','Software Engineering'],color:'mint'},
{id:'m9',name:'Meera Joshi',title:'Senior Software Engineer',company:'Salesforce',experience:6,domain:'Software Engineering',expertise:['Data Structures','C++','System Design'],skills:['C++','Data Structures','Git','Python','System Design'],focus:'Problem solving and software engineering fundamentals',bio:'Meera supports early engineers in strengthening algorithms, code quality, and the ability to explain technical decisions.',interests:['Software Engineering','DSA'],color:'peach'},
{id:'m10',name:'Dev Malhotra',title:'Data Engineering Lead',company:'Snowflake',experience:10,domain:'Data Science',expertise:['SQL','Cloud Computing','Python'],skills:['SQL','Python','Cloud Computing','Git','Data Structures'],focus:'Data pipelines and cloud data foundations',bio:'Dev helps learners build dependable data pipelines and understand how data engineering supports analytics and machine learning.',interests:['Data Science','Cloud'],color:'blue'}];
export const resources: LearningResource[] = [
['r1','Deep Learning Foundations','Learning guide','Deep Learning','Build intuition for neural networks, backpropagation, and model evaluation.','Start with a small handwritten-digit classifier.|Compare a linear baseline against a two-layer network.|Use a held-out test set and explain where the model fails.'],
['r2','Introduction to MLOps','Project guide','MLOps','Turn a notebook experiment into a repeatable machine learning workflow.','Version your training code and record your dataset source.|Create a reproducible environment and save evaluation metrics.|Serve a trained model through a small local API.'],
['r3','Docker Fundamentals','Practice guide','Docker','Package an application with a reproducible development environment.','Learn the relationship between an image and a container.|Write a Dockerfile for a small Python application.|Use volumes for persistent data and document how to run it.'],
['r4','AWS Cloud Basics','Learning guide','Cloud Computing','Understand compute, storage, and the building blocks of cloud architecture.','Sketch how compute, object storage, and a database work together.|Explain identity permissions and least-privilege access.|Estimate the resources a sample application would need on paper.'],
['r5','Python for Machine Learning','Practice guide','Python','Strengthen the Python foundations behind your machine learning projects.','Load a small public tabular dataset and inspect missing values.|Use vectorized operations to transform the data.|Write reusable functions and test their behavior on edge cases.'],
['r6','Full Stack Foundations','Project guide','React','Build a thoughtful interface with reusable components and state.','Break a small application into reusable components.|Add accessible forms with clear validation.|Persist data locally and handle empty states.'],
['r7','Data Structures in Practice','Practice guide','Data Structures','Develop a clear approach to common programming problems.','Compare arrays, maps, and sets on the same problem.|Explain time and space complexity in plain language.|Test empty input, duplicates, and large inputs.'],
['r8','Security Fundamentals','Learning guide','Security','Learn the foundations of secure software design.','Model the assets and trust boundaries in a sample application.|Study input validation and safe handling of secrets.|Write a defensive checklist for your own local project.'],
['r9','Practical SQL','Practice guide','SQL','Build confidence extracting and organizing relational data.','Model a small dataset as related tables.|Practice joins, grouping, and aggregate functions.|Explain how null values affect each query.']
].map(([id,title,type,skill,description,content])=>({id,title,type,skill,description,content:content.split('|')}));
export const progress: ProgressRecord[] = [
{month:'Apr',Python:35,'Machine Learning':15,DSA:25,Cloud:5,MLOps:0},{month:'May',Python:44,'Machine Learning':24,DSA:32,Cloud:10,MLOps:5},{month:'Jun',Python:52,'Machine Learning':32,DSA:40,Cloud:16,MLOps:10},{month:'Jul',Python:60,'Machine Learning':41,DSA:46,Cloud:23,MLOps:18},{month:'Aug',Python:69,'Machine Learning':51,DSA:55,Cloud:30,MLOps:25},{month:'Sep',Python:78,'Machine Learning':62,DSA:64,Cloud:38,MLOps:34}];
export const learningTrend = [{week:'Week 1',activities:4},{week:'Week 2',activities:7},{week:'Week 3',activities:5},{week:'Week 4',activities:10},{week:'Week 5',activities:8},{week:'Week 6',activities:12}];
export const domainProgress = [{domain:'AI / ML',progress:62},{domain:'DSA',progress:64},{domain:'Cloud',progress:38},{domain:'DevOps',progress:34},{domain:'Full Stack',progress:22}];
export const initialActivities: ActivityLog[] = [{id:'seed1',action:'Updated skill profile',entity:'Python, Machine Learning Basics',timestamp:'2026-09-16T10:30:00.000Z',description:'Demo history · Added current skills to personalize career guidance.'},{id:'seed2',action:'Updated career goal',entity:profile.careerGoal,timestamp:'2026-09-15T09:00:00.000Z',description:'Demo history · Set a direction for the learning journey.'}];
