import test from 'node:test';
import assert from 'node:assert/strict';
import { getMatches, getRecommendations } from './engine';
import { profile, mentors } from './data';
import { loadData, persist, STORAGE_KEY } from './storage';
test('matching scores use the weighted overlaps and remain ordered',()=>{const results=getMatches(profile);assert.equal(results.length,10);for(const m of results){assert.equal(m.score,Math.round(Object.values(m.breakdown).reduce((a,b)=>a+b,0)));assert(m.score>=0&&m.score<=100);assert.equal(m.reasons.length,4);}assert(results.every((m,i)=>i===0||results[i-1].score>=m.score));const ananya=results.find(m=>m.mentor.id==='m1')!;assert.equal(ananya.breakdown.career,40);assert.equal(ananya.breakdown.desired,20);assert.equal(ananya.breakdown.existing,16);assert.equal(ananya.breakdown.interests,7.5);assert.equal(ananya.score,84);});
test('changing career and skills changes the recommended mentors and resources',()=>{const changed={...profile,careerGoal:'Full Stack Developer',skills:['Git','TypeScript'],desiredSkills:['React'],interests:['Full Stack']};assert.equal(getMatches(changed)[0].mentor.id,'m8');assert.notEqual(getMatches(profile)[0].mentor.id,getMatches(changed)[0].mentor.id);assert(getRecommendations(changed).resources.some(r=>r.skill==='React'));assert.notDeepEqual(getRecommendations(profile).skills,getRecommendations(changed).skills);});
test('empty profile arrays give finite results and do not invent overlap',()=>{const p={...profile,careerGoal:'',skills:[],desiredSkills:[],interests:[]};assert(getMatches(p).every(m=>m.score===0));assert.equal(getRecommendations(p).resources.length,0);});
test('local data round-trips and malformed persistence safely falls back',()=>{let value:string|null=null;Object.defineProperty(globalThis,'localStorage',{value:{getItem:()=>value,setItem:(key:string,v:string)=>{assert.equal(key,STORAGE_KEY);value=v}},configurable:true});const state=loadData();state.saved=[{id:mentors[0].id,kind:'mentor'}];state.comparison=['m1','m2'];persist(state);assert.deepEqual(loadData(),state);value='{broken';assert.equal(loadData().profile.name,profile.name);value=JSON.stringify({version:1,profile:{skills:5},saved:[null,{kind:'mentor',id:'bad'}],comparison:['bad','m1','m1'],activities:[null]});assert.deepEqual(loadData().comparison,['m1']);assert.equal(loadData().saved.length,0);});
